c3_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('main_homepage_app.urls')),
    path('admin/', admin.site.urls),
    path('claims/', include('claims_app.urls')),
    path('users/', include('users.urls')),
    path('sales/', include('sales_app.urls')),
    path('reports/', include('reports_app.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='users:login'), name='logout'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports_app/urls.py
from django.urls import path
from . import views

app_name = 'reports_app'

urlpatterns = [
    path('', views.reports_home, name='reports_home'),
    path('sales/', views.sales_report, name='sales_report'),
    path('claims/', views.claims_report, name='claims_report'),
]

sales_app/urls.py
from django.urls import path
from . import views

app_name = 'sales_app'

urlpatterns = [
    # Home page
    path('', views.sales_homepage, name='sales_homepage'),
    path('new_sale/', views.add_sale, name='add_sale'),
    path('new_product/', views.add_product, name='add_product'),
    path('view_sales/', views.see_sales, name='see_sales'),
    path('sale/<int:sale_id>', views.see_sale, name='see_sale'),
    path('view_products/', views.see_products, name='see_products'),
    path('product/<int:product_id>', views.see_product, name='see_product'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('dealerjobs/', views.see_dealer_jobs, name='see_dealer_jobs'),
    path('dealerjob/<int:job_id>', views.see_dealer_job, name='see_dealer_job'),
]

urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('claims/', include('claims_app.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports_app/models.py
from django.db import models

# Create your models here.

reports_app/views.py
from django.shortcuts import render
from sales_app.models import Sale
from claims_app.models import Claim

# Create your views here.

def reports_home(request):
    # Add any necessary logic here
    return render(request, 'reports_app/reports_home.html')

def sales_report(request):
    # Fetch sales data from the database
    sales_data = Sale.objects.all()  # Example: Fetch all sales data
    
    # Pass the data to the template for rendering
    return render(request, 'reports_app/sales_report.html', {'sales_data': sales_data})

def claims_report(request):
    claims = Claim.objects.all()
    return render(request, 'reports_app/claims_report.html', {'claims': claims})

reports_app/templates/reports_app/claims_report.html
{% extends 'main_homepage_app/base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {     
            margin: 20px auto;
            margin-left: 20px;
            margin-right: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            padding-bottom: 10px;
            color: #333;
            text-align: center;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f8f8f8;
        }
        tr:hover {
        background-color: #f0f0f0;
        cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Claims Summary</h1>
        <table>
            <thead>
                <tr>
                    <th>Claim ID</th>
                    <th>Claim Type</th>
                    <th>Claim Date</th>
                    <th>Claim Status</th>
                </tr>
            </thead>
            <tbody>
                {% for claim in claims %}
                <tr>
                    <td>{{ claim.claim_id }}</td>
                    <td>{{ claim.claim_type }}</td>
                    <td>{{ claim.claim_date }}</td>
                    <td>{{ claim.claim_status }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var rows = document.querySelectorAll(".clickable-row");
            rows.forEach(function(row) {
                row.addEventListener("click", function() {
                    window.location.href = row.getAttribute("data-href");
                });
            });
        });
    </script>
</body>
</html>

{% endblock content %}

reports_app/templates/reports_app/reports_home.html
{% extends 'main_homepage_app/base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reports Homepage</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            margin: 20px auto;
            margin-left: 20px;
            margin-right: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            padding-bottom: 10px;
            color: #333;
            text-align: center;
            
        }
        h3 {
            margin: 5px;
            color: #333;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Reports Homepage</h1>
        <h2>Welcome C3 staff! Choose a report type below:</h2>
        <ul>
            <li><h3><a href="{% url 'reports_app:sales_report' %}">Sales Report</a></h3></li>
            <li><h3><a href="{% url 'reports_app:claims_report' %}">Claims Report</a></h3></li>
            <!-- Add links to other reports or summaries -->
        </ul>
    </div>
</body>
</html>

{% endblock content %}

reports_app/templates/reports_app/sales_report.html
{% extends 'main_homepage_app/base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {     
            margin: 20px auto;
            margin-left: 20px;
            margin-right: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            padding-bottom: 10px;
            color: #333;
            text-align: center;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f8f8f8;
        }
        tr:hover {
        background-color: #f0f0f0;
        cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Sales Report</h1>
        <table>
            <thead>
                <tr>
                    <th>Sale ID</th>
                    <th>Date</th>
                    <th>Customer</th>
                    <th>Digital Signature</th>
                    <th>Product</th>
                </tr>
            </thead>
            <tbody>
                {% for sale in sales_data %}
                <tr class='clickable-row' data-href="{% url 'sales_app:see_sale' sale.sale_id %}">
                    <td>{{ sale.sale_id }}</td>
                    <td>{{ sale.sale_date }}</td>
                    <td>{{ sale.customer }}</td>
                    <td>{{ sale.digital_signature}}</td>
                    <td>{{ sale.product}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var rows = document.querySelectorAll(".clickable-row");
            rows.forEach(function(row) {
                row.addEventListener("click", function() {
                    window.location.href = row.getAttribute("data-href");
                });
            });
        });
    </script>
</body>
</html>

{% endblock content %}