c3_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('main_homepage_app.urls')),
    path('admin/', admin.site.urls),
    path('claims/', include('claims_app.urls')),
    path('users/', include('users.urls')),
    path('sales/', include('sales_app.urls')),
    path('reports/', include('reports_app.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='users:login'), name='logout'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

claims_app/urls.py
from django.urls import path
from . import views

app_name = 'claims_app'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('get_claims/',views.get_claims, name='get_claims'),
    path('get_claims/<int:claim_id>', views.get_claim, name='get_claim'),
    path('new_claim/<int:sale_id>', views.new_claim, name='new_claim'),
    path('claim_repairs/',views.get_claim_repairs, name='get_claim_repairs'),
    path('claim_repairs/<int:repair_id>', views.get_claim_repair, name='get_claim_repair'),
]

sales_app/urls.py
from django.urls import path
from . import views

app_name = 'sales_app'

urlpatterns = [
    # Home page
    path('', views.sales_homepage, name='sales_homepage'),
    path('new_sale/', views.add_sale, name='add_sale'),
    path('new_product/', views.add_product, name='add_product'),
    path('view_sales/', views.see_sales, name='see_sales'),
    path('sale/<int:sale_id>', views.see_sale, name='see_sale'),
    path('view_products/', views.see_products, name='see_products'),
    path('product/<int:product_id>', views.see_product, name='see_product'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('dealerjobs/', views.see_dealer_jobs, name='see_dealer_jobs'),
    path('dealerjob/<int:job_id>', views.see_dealer_job, name='see_dealer_job'),
]

urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('claims/', include('claims_app.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

claims_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Claim(models.Model):
    claim_id = models.AutoField(primary_key=True)
    claim_type = models.IntegerField() # 1 for: Product Warranty Claim, 2 for: Extended Warranty Claim
    claim_desc = models.CharField(max_length = 200)
    claim_date = models.DateField()
    decision_date = models.DateField(null=True)
    claim_photo = models.ImageField(upload_to='images/', height_field=None, width_field=None, max_length=100)
    claim_status = models.IntegerField(default=0) # 0 for: Under Review, 1 for: Denied, 2 for: Accepted
    sale_id = models.ForeignKey('sales_app.Sale', on_delete=models.CASCADE)
    deciding_staff = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Claim ID: {self.claim_id}, Claim Date: {self.claim_date}"
    
class ClaimRepair(models.Model):
    repair_id = models.AutoField(primary_key=True)
    repair_desc = models.CharField(max_length = 200, null=True)
    repair_date = models.DateField(null=True)
    repair_photo = models.ImageField(upload_to='images/', height_field=None, width_field=None, max_length=100, null=True)
    repair_status = models.IntegerField(default=1) # 1 for: Ready for Repair, 2 for: Repaired
    claim_id = models.ForeignKey(Claim, on_delete=models.CASCADE)
    repair_staff = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Repair ID: {self.repair_id}"

claims_app/forms.py
#claims_app/forms.py
from django import forms
from .models import Claim, ClaimRepair

class ClaimForm(forms.ModelForm):

    class Meta:
        model = Claim
        fields = ('claim_desc', 'claim_photo')
        exclude = ['claim_type', 'claim_id', 'claim_date', 'claim_status', 'deciding_staff', 'sale_id']
        
class ClaimReviewForm(forms.ModelForm):
    CHOICES1 = (
            (1, 'Deny Claim'),
            (2, 'Approve Claim'),
        )
        
    claim_status = forms.ChoiceField(choices=CHOICES1, label='Approve claim?')

    class Meta:
        model = Claim
        fields = ('claim_status',)
        exclude = ['claim_id', 'claim_type', 'claim_date', 'claim_desc', 'claim_photo', 'sale_id', 'deciding_staff']

class ClaimRepairForm(forms.ModelForm):
    CHOICES2 = (
            (2, 'Repaired'),
            (3, 'Unable to Repair'),
        )
        
    repair_status = forms.ChoiceField(choices=CHOICES2, label='Indicate Status of Repair')

    class Meta:
        model = ClaimRepair
        fields = ('repair_status', 'repair_desc', 'repair_photo')
        exclude = ['repair_id', 'repair_date', 'claim_id', 'repair_staff']

    def __init__(self, *args, **kwargs):
        super(ClaimRepairForm, self).__init__(*args, **kwargs)
        self.fields['repair_photo'].required = False

# Jaiden waz here

claims_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Claim, ClaimRepair
from sales_app.models import Sale
from .forms import ClaimForm, ClaimReviewForm, ClaimRepairForm
from datetime import date


# Create your views here.
def index(request):
    """The home page for Claims."""
    return render(request, 'claims_app/index.html')

@login_required
def get_claims(request):
    """Find all claims"""
    claimslistcust = Claim.objects.filter(sale_id__customer=request.user).order_by('claim_id')
    claimslist = Claim.objects.order_by('claim_id')
    context={'Claims':claimslist, 'CustClaims':claimslistcust}

    return render(request, 'claims_app/get_claims.html', context)

@login_required
def get_claim(request, claim_id):
    """Show a single claim and its contents."""
    myclaim = Claim.objects.get(pk=claim_id)
    if request.method == 'POST':
        form = ClaimReviewForm(request.POST, request.FILES, instance=myclaim)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.claim_id = claim_id
            instance.decision_date = date.today()
            instance.deciding_staff = request.user
            instance.save()
            return redirect('claims_app:get_claims')
        else:
            print(form.errors)  
    else:
        form = ClaimReviewForm()
    context = {'Claim': myclaim, 'form': form}
    return render(request, 'claims_app/get_claim.html', context)

@login_required
def new_claim(request, sale_id):
    """Add a new claim."""
    mysale = Sale.objects.get(pk=sale_id)
    if request.method == 'POST':
        form = ClaimForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False) 
            instance.claim_type = mysale.product.product_type
            instance.claim_date = date.today()
            instance.claim_status = 0
            instance.sale_id = mysale
            instance.save() 
            return redirect('claims_app:index') 
        else:
            print(form.errors) 
    else:
        form = ClaimForm()
    return render(request, 'claims_app/new_claim.html', {'form': form})

@login_required
def get_claim_repairs(request):
    repairslistcust = ClaimRepair.objects.filter(claim_id__sale_id__customer=request.user).order_by('claim_id')
    repairslist = ClaimRepair.objects.order_by('repair_id')
    context={'ClaimRepairs':repairslist, 'CustRepairs':repairslistcust}

    return render(request, 'claims_app/get_claim_repairs.html', context)

# Hi Robb

@login_required
def get_claim_repair(request, repair_id):
    myrepair = ClaimRepair.objects.get(pk=repair_id)
    if request.method == 'POST':
        form = ClaimRepairForm(request.POST, request.FILES, instance=myrepair)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.repair_id = repair_id
            instance.repair_date = date.today()
            instance.repair_staff = request.user
            instance.save()
            return redirect('claims_app:get_claim_repairs')
        else:
            print(form.errors) 
    else:
        form = ClaimRepairForm()
    context = {'ClaimRepair': myrepair, 'form': form}
    return render(request, 'claims_app/get_claim_repair.html', context)

claims_app/templates/claims_app/base.html
<p><a href="{% url 'claims_app:index'%}">
Claim</a> -  
<a href="{% url 'claims_app:get_claims'%}">
Find Claim</a></p>
{% block content %} to be overridden
{% endblock content %}
    

claims_app/templates/claims_app/get_claim.html
{% extends 'main_homepage_app/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Claim Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            padding-bottom: 10px;
            color: #333;
            text-align: center;
        }
        h3 {
            color: #333;
            
        }
        h2 {
            color: #333;
            text-align: center;
        }
        p {
            font-size: 16px;
            margin-bottom: 10px;
            color: #666;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
        img {
            max-width: 100%;
            height: auto;
            margin-top: 10px;
        }
        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        input[type="text"],
        input[type="number"],
        input[type="file"],
        select {
            width: calc(100% - 20px);
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
            margin-bottom: 10px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Claim Details</h1>
        <h3>Claim #{{ Claim.claim_id }}</h3>
        <ul><p>Claim Details:</p>
            <li>Description of issue: {{ Claim.claim_desc }}</li>
            <li>Claim date: {{ Claim.claim_date }}</li>
            {% if Claim.claim_status == 0 %}
                <li>Under Review</li>
            {% elif Claim.claim_status == 1 %}
                <li>Claim denied</li>
            {% elif Claim.claim_status == 2 %}
                <li>Claim Approved</li>
            {% endif %}
            {% if Claim.claim_photo %}
                <img src="{{ Claim.claim_photo.url }}" alt="Claim Photo">
            {% endif %}
        </ul>
        {% if Claim.claim_status == 0 %}
            <p><i>For employees</i></p>   
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit Review</button>
            </form>
        {% else %}
            <p></p>
            <p><i>For employees</i></p>
            <p>This claim has been reviewed on {{ Claim.decision_date }} by {{ Claim.deciding_staff }}</p>
        {% endif %}
    </div>
</body>
</html>
{% endblock content %}

claims_app/templates/claims_app/get_claim_repair.html
{% extends 'main_homepage_app/base.html' %}
{% load custom_filters %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Claim Repair Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            padding-bottom: 10px;
            color: #333;
            text-align: center;
        }
        h3 {
            color: #333;
            margin-top: 10px;
        }
        p {
            font-size: 16px;
            margin-bottom: 10px;
            color: #666;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
        img {
            max-width: 100%;
            height: auto;
            margin-top: 10px;
        }
        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        input[type="text"],
        input[type="number"],
        input[type="file"],
        select {
            width: calc(100% - 20px);
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
            margin-bottom: 10px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Claim Repair Details</h1>
        <h3>Claim Repair: {{ ClaimRepair.repair_id }}</h3>
        <ul>
            {% if ClaimRepair.repair_status == 1 %}
            <li>Claim awaiting repair</li>
            <li>Date claim approved for repair: {{ ClaimRepair.claim_id.decision_date }}</li>
            <li>Repair deadline: Deadline: {{ ClaimRepair.claim_id.decision_date|add_days:7 }}</li>
            {% else %}
            <li>Repair closed on {{ ClaimRepair.repair_date }}</li>
            {% endif %}
            <li>Issue described in claim: {{ ClaimRepair.claim_id.claim_desc }}</li>
            {% if ClaimRepair.claim_id.claim_photo %}
            <li>Photo provided in claim:
                <img src="{{ ClaimRepair.claim_id.claim_photo.url }}" alt="Claim Photo">
            </li>
            {% endif %}
        </ul>
        {% if ClaimRepair.repair_status == 1 %}
            <p><i>For Dealership</i></p>
            <p>Repair Details Form:</p>   
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Close Repair Request</button>
            </form>
        {% else %}
            <p>This repair has been closed on {{ ClaimRepair.repair_date }} by {{ ClaimRepair.repair_staff }}</p>
            <ul>
                <li>Repair description: {{ ClaimRepair.repair_desc }}</li>
                <li>Repair Result: 
                    {% if ClaimRepair.repair_status == 2 %}
                        Repaired
                    {% elif ClaimRepair.repair_status == 3 %}
                        Unable to be repaired
                    {% endif %}
                </li>
            </ul>
            {% if ClaimRepair.repair_photo %}
                <img src="{{ ClaimRepair.repair_photo.url }}" alt="Repair Photo">
            {% endif %}
        {% endif %}
    </div>
</body>
</html>
{% endblock content %}


claims_app/templates/claims_app/get_claim_repairs.html
{% extends 'main_homepage_app/base.html' %}
{% load custom_filters %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Product Application</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            margin: 20px auto;
            margin-right: 20px;
            margin-left: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            margin-top: 20px;
            font-size: 36px;
            color: #333;
            text-align: center;
        } 
        h2, h3, h4 {
            margin-top: 20px;
            color: #333;
        }
        p {
            margin-top: 10px;
            line-height: 1.6;
            color: #666;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Approved Claim Repairs</h1>
        <p><i>For customers - filter visible repairs by user</i></p>
        <h2>Here are your claims being repaired by dealerships:</h2>

        <h4>Awaiting Repair</h4>
        <ul>
            {% for repair in CustRepairs %}
                {% if repair.repair_status == 1 %}
                    <li>
                        <a href="{% url 'claims_app:get_claim_repair' repair.repair_id %}">{{ repair }} - Deadline: {{ repair.claim_id.decision_date|add_days:7 }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No claims are awaiting repair.</li>
            {% endfor %}
        </ul>

        <h4>Repaired</h4>
        <ul>
            {% for repair in CustRepairs %}
                {% if repair.repair_status == 2 %}
                    <li>
                        <a href="{% url 'claims_app:get_claim_repair' repair.repair_id %}">{{ repair }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No claims have been repaired yet.</li>
            {% endfor %}
        </ul>

        <h4>Unable to Repair</h4>
        <ul>
            {% for repair in CustRepairs %}
                {% if repair.repair_status == 3 %}
                    <li>
                        <a href="{% url 'claims_app:get_claim_repair' repair.repair_id %}">{{ repair }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No approved claims have failed to have been repaired.</li>
            {% endfor %}
        </ul>

        <p><i>For employees and dealerships</i></p>
        <h2>Dealership Repair Jobs</h2>
        <p>Repairs are to be complete no later than a week following the claim approval date!</p>

        <h4>Awaiting Repair</h4>
        <ul>
            {% for repair in ClaimRepairs %}
                {% if repair.repair_status == 1 %}
                    <li>
                        <a href="{% url 'claims_app:get_claim_repair' repair.repair_id %}">{{ repair }} - Deadline: {{ repair.claim_id.decision_date|add_days:7 }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No claims are awaiting repair.</li>
            {% endfor %}
        </ul>

        <h4>Repaired</h4>
        <ul>
            {% for repair in ClaimRepairs %}
                {% if repair.repair_status == 2 %}
                    <li>
                        <a href="{% url 'claims_app:get_claim_repair' repair.repair_id %}">{{ repair }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No claims have been repaired yet.</li>
            {% endfor %}
        </ul>

        <h4>Unable to Repair</h4>
        <ul>
            {% for repair in ClaimRepairs %}
                {% if repair.repair_status == 3 %}
                    <li>
                        <a href="{% url 'claims_app:get_claim_repair' repair.repair_id %}">{{ repair }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No approved claims have failed to have been repaired.</li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>
{% endblock content %}

claims_app/templates/claims_app/get_claims.html
{% extends 'main_homepage_app/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Claim Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            margin: 20px auto;
            margin-right: 20px;
            margin-left: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            padding-bottom: 10px;
            color: #333;
            text-align: center;
        }
        h2, h4 {
            margin-top: 20px;
            color: #333;
        }
        p {
            font-size: 16px;
            margin-bottom: 10px;
            color: #666;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Claim Details</h1>
        <p><i>For customers - filter claims by user</i></p>
        <h2>Your Claim History</h2>
        <div>
            <h4>Yet to be reviewed</h4>
            <ul>
                {% for claim in CustClaims %}
                    {% if claim.claim_status == 0 %}
                        <li>
                            <a href="{% url 'claims_app:get_claim' claim.claim_id %}">{{ claim }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>No claims have been added yet</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h4>Approved</h4>
            <ul>
                {% for claim in CustClaims %}
                    {% if claim.claim_status == 2 %}
                        <li>
                            <a href="{% url 'claims_app:get_claim' claim.claim_id %}">{{ claim }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>No claims have been approved yet</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h4>Denied</h4>
            <ul>
                {% for claim in CustClaims %}
                    {% if claim.claim_status == 1 %}
                        <li>
                            <a href="{% url 'claims_app:get_claim' claim.claim_id %}">{{ claim }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>No claims have been denied yet</li>
                {% endfor %}
            </ul>
        </div>
        <h3><a href="{% url 'sales_app:see_sales' %}">Make a claim on a previous purchase</a></h3>
        <p><i>For employees</i></p>
        <h2>All Claims</h2>
        <div>
            <h4>Yet to be reviewed</h4>
            <ul>
                {% for claim in Claims %}
                    {% if claim.claim_status == 0 %}
                        <li>
                            <a href="{% url 'claims_app:get_claim' claim.claim_id %}">{{ claim }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>No claims have been added yet</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h4>Approved</h4>
            <ul>
                {% for claim in Claims %}
                    {% if claim.claim_status == 2 %}
                        <li>
                            <a href="{% url 'claims_app:get_claim' claim.claim_id %}">{{ claim }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>No claims have been approved yet</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h4>Denied</h4>
            <ul>
                {% for claim in Claims %}
                    {% if claim.claim_status == 1 %}
                        <li>
                            <a href="{% url 'claims_app:get_claim' claim.claim_id %}">{{ claim }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>No claims have been denied yet</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>
{% endblock content %}

claims_app/templates/claims_app/index.html
{% extends 'main_homepage_app/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Claims Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            margin: 20px auto;
            margin-right: 20px;
            margin-left: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            padding-bottom: 10px;
            color: #333;
            text-align: center;
        }
        h3 {
            margin: 5px;
            color: #333;
        }
        p {
            font-size: 16px;
            margin-top: 10px;
            line-height: 1.6;
            color: #666;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to the Claims Page!</h1>
        <p><i>For customers</i></p>
        <h2>Need to make a claim?</h2>
        {% if user.is_authenticated %}
            <p>Go to your previous sales to begin the claim process</p>
            <ul>
                <li><h3><a href="{% url 'sales_app:see_sales' %}">Purchase History</a></h3></li>
            </ul>
            <p>Find your claims here:</p>
            <ul>
                <li><h3><a href="{% url 'claims_app:get_claims'%}">Check on a Previous Claim</a></h3></li>
            </ul>
            <p>View the repair status for approved claims:</p>
            <ul>
                <li><h3><a href="{% url 'claims_app:get_claim_repairs'%}">Claims Approved for Repair</a></h3></li>
            </ul>
            <p><i>For dealerships</i></p>
            <h3><a href="{% url 'claims_app:get_claim_repairs'%}">Claims Approved for Repair</a></h3>
            <p>View all claim repair jobs</p>
        {% else %}
            <a href="{% url 'users:login' %}">Please log in to make a claim</a>
        {% endif %}
    </div>
</body>
</html>
{% endblock content %}

claims_app/templates/claims_app/new_claim.html
{% extends 'main_homepage_app/base.html' %}
{% block content %}     
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Make a New Claim</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            color: #333;
            text-align: center;
        }
        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        input[type="text"],
        input[type="number"],
        input[type="file"],
        select {
            width: calc(100% - 20px);
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
            margin-bottom: 10px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Make a New Claim</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit Claim</button>
        </form>
    </div>
</body>
</html>
{% endblock content %}