c3_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('main_homepage_app.urls')),
    path('admin/', admin.site.urls),
    path('claims/', include('claims_app.urls')),
    path('users/', include('users.urls')),
    path('sales/', include('sales_app.urls')),
    path('reports/', include('reports_app.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='users:login'), name='logout'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

claims_app/urls.py
from django.urls import path
from . import views

app_name = 'claims_app'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('get_claims/',views.get_claims, name='get_claims'),
    path('get_claims/<int:claim_id>', views.get_claim, name='get_claim'),
    path('new_claim/<int:sale_id>', views.new_claim, name='new_claim'),
    path('claim_repairs/',views.get_claim_repairs, name='get_claim_repairs'),
    path('claim_repairs/<int:repair_id>', views.get_claim_repair, name='get_claim_repair'),
]

sales_app/urls.py
from django.urls import path
from . import views

app_name = 'sales_app'

urlpatterns = [
    # Home page
    path('', views.sales_homepage, name='sales_homepage'),
    path('new_sale/', views.add_sale, name='add_sale'),
    path('new_product/', views.add_product, name='add_product'),
    path('view_sales/', views.see_sales, name='see_sales'),
    path('sale/<int:sale_id>', views.see_sale, name='see_sale'),
    path('view_products/', views.see_products, name='see_products'),
    path('product/<int:product_id>', views.see_product, name='see_product'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('dealerjobs/', views.see_dealer_jobs, name='see_dealer_jobs'),
    path('dealerjob/<int:job_id>', views.see_dealer_job, name='see_dealer_job'),
]

urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('claims/', include('claims_app.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales_app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


# Create your models here.

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=50)
    product_type = models.IntegerField()
    product_price = models.DecimalField(max_digits=5, decimal_places=2)
    product_desc = models.CharField(max_length=200, null=True)
    product_photo = models.ImageField(upload_to='images/', height_field=None, width_field=None, max_length=100, null=True)
    employee = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"#{self.product_id}: {self.product_name} - ${self.product_price}"

class Sale(models.Model):
    sale_id = models.AutoField(primary_key=True)
    sale_date = models.DateField(default=date.today())
    digital_signature = models.CharField(max_length=20)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"Sale #{self.sale_id} - Product: {self.product.product_name} @ ${self.product.product_price}. Purchased by {self.customer}"
    
class DealerJob(models.Model):
    job_id = models.AutoField(primary_key=True)
    job_desc = models.CharField(max_length = 200, null=True)
    job_date = models.DateField(null=True)
    job_photo = models.ImageField(upload_to='images/', height_field=None, width_field=None, max_length=100, null=True)
    job_status = models.IntegerField(default=1) # 1 for: Ready for Application, 2 for: Applied
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    job_staff = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Job ID: {self.job_id}"

sales_app/forms.py
# sales_app/forms.py
from django import forms
from .models import Sale, Product, DealerJob

class ProductForm(forms.ModelForm):
    CHOICES1 = (
            (1, 'Regular Product'),
            (2, 'Extended Warranty'),
        )
        
    product_type = forms.ChoiceField(choices=CHOICES1, label='Product type')

    class Meta:
        model = Product
        fields = ('product_name', 'product_type', 'product_price', 'product_desc', 'product_photo')
        exclude = ['product_id', 'employee']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['product_photo'].required = False
        
class SaleForm(forms.ModelForm):

    class Meta:
        model = Sale
        fields = ('product', 'digital_signature')
        exclude = ['sale_id', 'customer', 'sale_date']

class DealerJobForm(forms.ModelForm):
    CHOICES2 = (
            (2, 'Product Applied'),
            (3, 'Unable to Apply Product'),
        )
        
    job_status = forms.ChoiceField(choices=CHOICES2, label='Indicate Status of Job')

    class Meta:
        model = DealerJob
        fields = ('job_status', 'job_desc', 'job_photo')
        exclude = ['job_id', 'job_date', 'sale', 'job_staff']

    def __init__(self, *args, **kwargs):
        super(DealerJobForm, self).__init__(*args, **kwargs)
        self.fields['job_photo'].required = False

sales_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import SaleForm, ProductForm, DealerJobForm
from .models import Sale, Product, DealerJob
from datetime import date

# Create your views here.
# Create your views here.
def sales_homepage(request):
    """The home page for Sales App."""
    return render(request, 'sales_app/sales_homepage.html')

@login_required
def thankyou(request):
    user = request.user
    return render(request, 'sales_app/thank_you.html', {'User':user})

@login_required
def see_sales(request):
    saleslistcust = Sale.objects.filter(customer=request.user).order_by('sale_id')
    saleslist = Sale.objects.order_by('sale_id')
    context={'Sales':saleslistcust, 'AllSales': saleslist}

    return render(request, 'sales_app/view_sales.html', context)

@login_required
def see_sale(request, sale_id):
    """Show a single sale and its contents."""
    mysale = Sale.objects.get(pk=sale_id)
    context = {'Sale': mysale}
    return render(request, 'sales_app/view_sale.html', context)

@login_required
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.employee = request.user
            instance.save()
            return redirect('sales_app:see_products')
        else:
            print(form.errors)  
    else:
        form = ProductForm()
    context = {'form': form}
    return render(request, 'sales_app/add_product.html', context)

@login_required
def see_products(request):
    productlist = Product.objects.order_by('product_id')
    context={'Products':productlist}

    return render(request, 'sales_app/view_products.html', context)

def see_product(request, product_id):
    myproduct = Product.objects.get(pk=product_id)
    context = {'Product': myproduct}
    return render(request, 'sales_app/view_product.html', context)

@login_required
def add_sale(request):
    if request.method == 'POST':
        form = SaleForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.customer = request.user
            instance.sale_date = date.today()
            instance.save()
            return redirect('sales_app:thankyou')
        else:
            print(form.errors)  
    else:
        form = SaleForm()
    context = {'form': form}
    return render(request, 'sales_app/add_sale.html', context)

@login_required
def see_dealer_jobs(request):
    custjobslist = DealerJob.objects.filter(sale__customer=request.user).order_by('job_id')
    jobslist = DealerJob.objects.order_by('job_id')
    context={'Jobs':jobslist, 'CustJobs':custjobslist}

    return render(request, 'sales_app/view_jobs.html', context)

# Hi Robb

@login_required
def see_dealer_job(request, job_id):
    myjob = DealerJob.objects.get(pk=job_id)
    if request.method == 'POST':
        form = DealerJobForm(request.POST, request.FILES, instance=myjob)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.job_id = job_id
            instance.job_date = date.today()
            instance.job_staff = request.user
            instance.save()
            return redirect('sales_app:see_dealer_jobs')
        else:
            print(form.errors) 
    else:
        form = DealerJobForm()
    context = {'Job': myjob, 'form': form}
    return render(request, 'sales_app/view_job.html', context)

sales_app/templates/sales_app/index.html
<!-- sales_app/templates/sales_app/index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to C3 Sales</title>
</head>
<body>
    <header>
        <h1>Welcome to C3 Sales</h1>
    </header>
    <main>
        <p>This is the Sales page of our website.</p>
        <!-- Add more content as needed -->
    </main>
    <footer>
        <!-- Footer content -->
    </footer>
</body>
</html>

sales_app/templates/sales_app/sales_homepage.html
<!-- sales_app/templates/sales_app/index.html -->
{% extends 'main_homepage_app/base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to C3 Sales</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            margin: 20px auto;
            margin-right: 20px;
            margin-left: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            margin-top: 20px;
            font-size: 36px;
            color: #333;
            text-align: center;
        }
        h2 {
            font-size: 24px;
            color: #007bff;
            margin-top: 30px;
        }
        h3 {
            font-size: 20px;
            margin-top: 20px;
        }
        p {
            margin-top: 10px;
            line-height: 1.6;
            color: #666;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
        .cta {
            text-align: center;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <div class="container">
        <p><i>For customers</i></p>
        <h1>Welcome to C3 Sales</h1>
        {% if user.is_authenticated %}
            <div class="cta">
                <h3><a href="{% url 'sales_app:add_sale' %}">Click Here to Make a Purchase!</a></h3>
            </div>
            <h2><p><a href="{% url 'sales_app:see_sales' %}">Purchase History</a></p></h2>
            <p>View all your previous purchases with C3</p>
            <h2><p><a href="{% url 'sales_app:see_products' %}">Products List</a></p></h2>
            <p>View all of our products and warranties!</p>
            <h2><p><a href="{% url 'sales_app:see_dealer_jobs' %}">Vehicle Product Application</a></p></h2>
            <p>View the status of any products being applied to your vehicle by our partnered dealerships</p>
            <p><i>For employees</i></p>
            <h1>Employee Sales Portal</h1>
            <h2><p><a href="{% url 'sales_app:add_product' %}">Add New Product</a></p></h2>
            <h2><p><a href="{% url 'sales_app:see_products' %}">See All Products</a></p></h2>
            <h2><p><a href="{% url 'sales_app:see_sales' %}">See All Sales</a></p></h2>
            <h2><p><a href="{% url 'sales_app:see_dealer_jobs' %}">Product Application Status</a></p></h2>
            <p><i>For dealerships</i></p>
            <h1>Dealership Job Portal</h1>
            <h2><p><a href="{% url 'sales_app:see_dealer_jobs' %}">C3 Product Application Jobs</a></p></h2>
        {% else %}
            <a class="nav-link" href="{% url 'users:login' %}">Please log in</a>
        {% endif %}
        
    </div>
</body>
</html>
{% endblock content %}

sales_app/templates/sales_app/thank_you.html
{% extends 'main_homepage_app/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thank You For Your Purchase!</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        header {
            color: #000000;
            padding: 20px;
            text-align: center;
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
            border-bottom-left-radius: 8px;
            border-bottom-right-radius: 8px;
        }
        h1 {
            font-size: 28px;
            margin-top: 0;
        }
        p {
            font-size: 16px;
            margin-bottom: 10px;
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Thank you for choosing C3, {{ user }}!</h1>
            <p>Your purchase has been processed</p>
        </header>
        <p><a href="{% url 'sales_app:see_sales' %}">See your purchase here</a></p>
    </div>
</body>
{% endblock content %}

sales_app/templates/sales_app/view_job.html
{% extends 'main_homepage_app/base.html' %}
{% load custom_filters %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Job Summary</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            padding-bottom: 10px;
            color: #333;
            text-align: center;
        }
        h2 {
            color: #333;
            text-align: center;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        input[type="text"],
        input[type="number"],
        input[type="file"],
        select {
            width: calc(100% - 20px);
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #ccc;
            margin-bottom: 10px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button:hover {
            background-color: #0056b3;
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
        img {
            max-width: 100%;
            height: auto;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Dealership Job Summary</h1>
        <h3>Product Application #{{ Job.job_id }} (Sale #{{ Job.sale.sale_id }})</h3>
        <h3>Product to be applied: <a href="{% url 'sales_app:see_product' Job.sale.product.product_id %}">{{ Job.sale.product.product_name }}</a></h3>
        <h3>Deadline: {{ Job.sale.sale_date|add_days:7 }}</h3>
        {% if Job.job_status == 1 %}
            <p>Job Awaiting Completion</p>  
            <p><i>For Dealership</i></p>
            <h2>Job Details Form</h2>   
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Close Job</button>
            </form>
        {% else %}
        <ul>
            <li>This job has been completed on {{ Job.job_date }} by {{ Job.job_staff }}</li>
            <li>Job description: {{ Job.job_desc }}</li>
            <li>Job Result: 
                {% if Job.job_status == 2 %}
                    Product Applied
                {% elif Job.job_status == 3 %}
                    Unable to apply product
                {% endif %}
            </li>
        
        {% if Job.job_photo %}
            <li><p>Repair Photo:</p>
            <img src="{{ Job.job_photo.url }}" alt="Repair Photo"></li>
        </ul>
        {% endif %}
        {% endif %}
    </div>
</body>
</html>
{% endblock content %}

sales_app/templates/sales_app/view_jobs.html
{% extends 'main_homepage_app/base.html' %}
{% load custom_filters %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Product Application</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            margin: 20px auto;
            margin-right: 20px;
            margin-left: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            margin-top: 20px;
            font-size: 36px;
            color: #333;
            text-align: center;
        } 
        h2, h3, h4 {
            margin-top: 20px;
            color: #333;
        }
        p {
            margin-top: 10px;
            line-height: 1.6;
            color: #666;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Vehicle Product Application</h1>
        <p><i>For customers - filter visible jobs by user</i></p>
        <h2>Here are all your purchases being applied by dealerships:</h2>

        <h4>Awaiting Application</h4>
        <ul>
            {% for job in CustJobs %}
                {% if job.job_status == 1 %}
                    <li>
                        <a href="{% url 'sales_app:see_dealer_job' job.job_id %}">{{ job }} - Deadline: {{ job.sale.sale_date|add_days:7 }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>You have no purchases awaiting application</li>
            {% endfor %}
        </ul>

        <h4>Product Applied</h4>
        <ul>
            {% for job in CustJobs %}
                {% if job.job_status == 2 %}
                    <li>
                        <a href="{% url 'sales_app:see_dealer_job' job.job_id %}">{{ job }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>None of your purchases have been applied</li>
            {% endfor %}
        </ul>

       
        <h4>Product Unable to be Applied</h4>
        <ul>
            {% for job in CustJobs %}
                {% if job.job_status == 3 %}
                    <li>
                        <a href="{% url 'sales_app:see_dealer_job' job.job_id %}">{{ job }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No sales were failed to be applied</li>
            {% endfor %}
        </ul>

        <p><i>For employees and dealerships</i></p>
        <h2>Dealership Product Application Jobs</h2>
        <p>Jobs are to be complete no later than a week following the sale!</p>

        <h4>Awaiting Application</h4>
        <ul>
            {% for job in Jobs %}
                {% if job.job_status == 1 %}
                    <li>
                        <a href="{% url 'sales_app:see_dealer_job' job.job_id %}">{{ job }} - Deadline: {{ job.sale.sale_date|add_days:7 }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No purchases are awaiting application</li>
            {% endfor %}
        </ul>

        <h4>Product Applied</h4>
        <ul>
            {% for job in Jobs %}
                {% if job.job_status == 2 %}
                    <li>
                        <a href="{% url 'sales_app:see_dealer_job' job.job_id %}">{{ job }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No purchases have been applied</li>
            {% endfor %}
        </ul>

       
        <h4>Product Unable to be Applied</h4>
        <ul>
            {% for job in Jobs %}
                {% if job.job_status == 3 %}
                    <li>
                        <a href="{% url 'sales_app:see_dealer_job' job.job_id %}">{{ job }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>No sales were failed to be applied</li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>
{% endblock content %}

sales_app/templates/sales_app/view_products.html
{% extends 'main_homepage_app/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            margin: 20px auto;
            margin-right: 20px;
            margin-left: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            margin-top: 20px;
            font-size: 36px;
            color: #333;
            text-align: center;
        }
        h3, h4 {
            margin-top: 20px;
            color: #333;
        }
        p {
            margin-top: 10px;
            line-height: 1.6;
            color: #666;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Product List</h1>
        
        <h2>Here are our products and warranties:</h2>
        <div>
          <h4>Regular Products</h4>
          <ul>
              {% for product in Products %}
                  {% if product.product_type == 1 %}
                      <li>
                          <a href="{% url 'sales_app:see_product' product.product_id %}">{{ product }}</a>
                      </li>
                  {% endif %}
              {% empty %}
                  <li>There are no regular products yet.</li>
              {% endfor %}
          </ul>
        </div>
        <h4>Extended Warranties</h4>
        <ul>
            {% for product in Products %}
                {% if product.product_type == 2 %}
                    <li>
                        <a href="{% url 'sales_app:see_product' product.product_id %}">{{ product }}</a>
                    </li>
                {% endif %}
            {% empty %}
                <li>There are no warranties yet.</li>
            {% endfor %}
        </ul>

        <p><i>For customers</i></p>
        <h3><a href="{% url 'sales_app:add_sale' %}">Purchase Something Here!</a></h3>

        <p><i>For employees</i></p>
        <h3><a href="{% url 'sales_app:add_product' %}">Add new products</a></h3>
    </div>
</body>
</html>
{% endblock content %}

sales_app/templates/sales_app/view_sales.html
{% extends 'main_homepage_app/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sale Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            margin: 20px auto;
            margin-right: 20px;
            margin-left: 20px;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 28px;
            padding-bottom: 10px;
            color: #333;
            text-align: center;
        }
        h3, h4 {
            color: #333;
            margin-top: 20px;
        }
        p {
            font-size: 16px;
            margin-bottom: 10px;
            color: #666;
        }
        ul {
            list-style-type: none;
            padding-left: 0;
            margin-top: 10px;
        }
        li {
            margin-bottom: 10px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        a {
            color: #007bff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
      <p><i>For customers - filter sales by user</i></p>
        <h1>Purchase History</h1>
        <h3>Here are all of your previous purchases with us:</h3>
        <div>
            <h4>Regular Products</h4>
            <ul>
                {% for sale in Sales %}
                    {% if sale.product.product_type == 1 %}
                        <li>
                            <a href="{% url 'sales_app:see_sale' sale.sale_id %}">{{ sale }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>You haven't made any regular product purchases yet.</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h4>Extended Warranties</h4>
            <ul>
                {% for sale in Sales %}
                    {% if sale.product.product_type == 2 %}
                        <li>
                            <a href="{% url 'sales_app:see_sale' sale.sale_id %}">{{ sale }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>You haven't made any extended warranty purchases yet.</li>
                {% endfor %}
            </ul>
        </div>

        <h3><a href="{% url 'sales_app:add_sale' %}">Make a new purchase</a></h3>

        <p><i>For employees</i></p>
        <h1>All Sales</h1>
        <div>
            <h4>Regular Products</h4>
            <ul>
                {% for sale in AllSales %}
                    {% if sale.product.product_type == 1 %}
                        <li>
                            <a href="{% url 'sales_app:see_sale' sale.sale_id %}">{{ sale }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>There haven't been any regular product purchases yet.</li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h4>Extended Warranties</h4>
            <ul>
                {% for sale in AllSales %}
                    {% if sale.product.product_type == 2 %}
                        <li>
                            <a href="{% url 'sales_app:see_sale' sale.sale_id %}">{{ sale }}</a>
                        </li>
                    {% endif %}
                {% empty %}
                    <li>There haven't been any extended warranty purchases yet.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>
{% endblock content %}